apiVersion: v1
kind: Template
metadata:
  name: ${PARAM_APP_NAME}
  annotations:
    description: "Template para aplicacion ${PARAM_APP_NAME}"

parameters:
  - name: PARAM_SOURCE_PROJECT
    displayName: Nombre del proyecto
    description: Nombre del proyecto en openshift.
    required: true
  - name: PARAM_APP_NAME
    displayName: Nombre de la aplicacion
    description: Nombre de la aplicacion en el proyecto de openshift.
    required: true
  - name: PARAM_URL
    displayName: URL de la aplicacion
    description: URL de la aplicacion en el proyecto de openshift.
    required: true


objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${PARAM_APP_NAME}
    template:
      metadata:
        labels:
          app: ${PARAM_APP_NAME}
      spec:
        containers:
          - image: ${PARAM_SOURCE_PROJECT}/${PARAM_APP_NAME}:latest
            imagePullPolicy: Always
            name: ${PARAM_APP_NAME}
            ports:
              - containerPort: 9000
                protocol: TCP

