apiVersion: v1
kind: Template
metadata:
  name: ${PARAM_APP_NAME}
  annotations:
    description: "Template para aplicacion ${PARAM_APP_NAME}"
    iconClass: "icon-symfony"
    tags: "web,php,symphony"

parameters:
  - name: PARAM_APP_NAME
    displayName: Nombre de la aplicacion
    description: Nombre de la aplicacion en el proyecto de openshift.
    required: true
  - name: PARAM_URL
    displayName: URL de la aplicacion
    description: URL de la aplicacion en el proyecto de openshift.
    required: true
  - name: PARAM_PROJECT_NAME
    display: false
    required: false


objects:

#### CONFIGMAP ####


- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: 00-documentroot
  data:
    00-documentroot.conf: |-
        <VirtualHost *:80>
            DocumentRoot "/opt/app-root/src/"
            DirectoryIndex index.php
            <Directory "/opt/app-root/src/">
                Options -Indexes +FollowSymLinks
                LimitRequestBody 2097152
                AllowOverride All
                Require all granted
            </Directory>
            <Directory "/opt/app-root/src/vendor/">
                AllowOverride None
                Order Allow,Deny
                Require all granted
            </Directory>
            <FilesMatch "^\.env|.gitignore|.htaccess|.gitattributes|.eslintrc|.gherkin-lintrc|package.json|composer.json|composer.lock|.jshintrc|.nvmrc|.jshintignore|.stylelintrc|.shifter.json|.travis.yml|Gruntfile.js|npm-shrinkwrap.json|.grunt|.github">
                Require all denied
            </FilesMatch> 
            CustomLog /dev/stdout combined
            ErrorLog /dev/stderr
        </VirtualHost>



- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: 01-seguridad
  data:
    01-seguridad.conf: |-
        ServerSignature Off
        ServerTokens Prod
        
        Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
        RewriteEngine On
        RewriteCond %{REQUEST_METHOD} ^TRACE
        RewriteRule .* -[F]
        RewriteCond %{REQUEST_METHOD} ^TRACK
        RewriteRule .* -[F]
        
        TraceEnable off
        Header set Cache-Control "no-cache, no-store, must-revalidate, private"
        Header set Pragma "no-cache"
        Header set Expires 0


#### DEPLOYCONFIG ####


- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      app: ${PARAM_APP_NAME}
      deploymentconfig: ${PARAM_APP_NAME}
    template:
      metadata:
        labels:
          app: ${PARAM_APP_NAME}
          deploymentconfig: ${PARAM_APP_NAME}
      spec:
        replicas: 1
        containers:

        # Container PHP
        - name: ${PARAM_APP_NAME}
          image: ${PARAM_APP_NAME}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: "0.9"
              memory: 2Gi
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
                - cat
                - /opt/app-root/src/index.php
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
    
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: TZ
              value: America/Argentina/Buenos_Aires
          volumeMounts:
            - name: documentroot
              mountPath: /etc/httpd/conf.d/00-documentroot.conf
              subPath: 00-documentroot.conf
            - name: seguridad
              mountPath: /etc/httpd/conf.d/01-seguridad.conf
              subPath: 01-seguridad.conf                           
            - name: ${PARAM_APP_NAME}-configuration-volume
              mountPath: /opt/app-root/src/config.php
              subPath: config.php
            - name: ${PARAM_APP_NAME}-configuration-env-volume
              mountPath: /opt/app-root/src/.env
              subPath: .env
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: documentroot
            configMap:
              name: 00-documentroot
              defaultMode: 420
          - name: seguridad
            configMap:
              name: 01-seguridad
              defaultMode: 420
          - name: htaccess
            configMap:
              name: 00-htaccess
              defaultMode: 420                              
          - name: ${PARAM_APP_NAME}-configuration-volume
            configMap:
              defaultMode: 420
              name: ${PARAM_APP_NAME}-configuration
          - name: ${PARAM_APP_NAME}-configuration-env-volume
            configMap:
              name: ${PARAM_APP_NAME}-configuration-env
    test: false


######### CLAIM upload ##########

- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-configuration

  data:
    config.php: |


- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-configuration-env
  data:
    .env: |


#### ROUTES ####

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    host: ${PARAM_URL}
    port:
      targetPort: http
    to:
      kind: Service
      name: ${PARAM_APP_NAME}

#### SERVICE ####

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${PARAM_APP_NAME}
      deploymentconfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
